# Generated by Django 5.0.6 on 2024-05-20 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('channel_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('imagine', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('user', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField()),
                ('description', models.TextField()),
                ('imagine', models.ImageField(upload_to='')),
                ('rss_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss', to='MovieNews.rssfeed')),
            ],
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='users',
            field=models.ManyToManyField(related_name='rss_list', to='MovieNews.user'),
        ),
    ]
