# Generated by Django 5.0.6 on 2024-05-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieNews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='rssfeed',
            options={'verbose_name': 'rss feed', 'verbose_name_plural': 'rss feed'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
