# Generated by Django 5.0.6 on 2024-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieNews', '0002_alter_news_options_alter_rssfeed_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='rss_list', to='MovieNews.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=18),
        ),
    ]
