# Generated by Django 5.0.6 on 2024-05-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieNews', '0003_alter_rssfeed_users_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='imagine',
        ),
    ]
