# Generated by Django 5.0.6 on 2024-05-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieNews', '0004_remove_news_imagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='rss_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='MovieNews.rssfeed'),
        ),
    ]
