# Generated by Django 5.0.6 on 2024-05-26 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieNews', '0005_news_short_description_alter_news_rss_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='imagine',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
